### ISSUE TITLE
Is this the right project for pre processor support?

### ISSUE THREAD

**Issue by toranb** [johnotander/ember-cli-csslint#3]
Just reading over the project readme and todos - wanted to see if this project *would/could/should* extend for SASS/SCSS support or if that was another addon for ember-cli altogether 

Regardless -thanks for such an awesome OSS project!

**Comment by scottrblock** [comment]
@johnotander I stumbled on this addon and issue when searching for something like `ember-cli-scss-lint`. I like the idea of linting based on which Broccoli linters are installed. Are you currently working on that? I didn't see a branch or anything here. I'm happy to fork and get started!

**Comment by johnotander** [comment]
Hey, cool!

Yeah, I haven't gotten the chance to get started yet. Feel free to go ahead and do just that. That'd be so awesome!

**Comment by scottrblock** [comment]
After a bit more research, I'm not sure this would be the best way to go about things, and would welcome some more feedback around the subject.

Looking at the ember-cli code to minify preprocessed css, it appears to not allow more than one minify-css plugin at once.- https://github.com/ember-cli/ember-cli/blob/05e1117df1faebf15afa2a134494da3db1405e27/lib/preprocessors.js#L34-L47. I'm not sure how much work it would be to allow multiple linters, but I'd think supporting at least 2- one for scss/less and one for the outputted css would be desirable.

To get started, it would certainly be easier to just use the great work @johnotander has already done here, and replace the linter with a scss one in a separate addon. 

I don't think, and this could probably be tested, that keeping the addons separate would slow down the build process, since scss and css files would need to be linted through in any scenario. With that in mind, having separate addons such as `ember-cli-csslint`, `ember-cli-scss-lint`, and `ember-cli-lesslint` would allow a future addon to simply require these smaller addons to create an all encompassing linter.

Would definitely appreciate some more feedback, especially from @johnotander and @toranb, but to me keeping them separate makes things easier for now, while preserving maximum flexibility down the line. If you want to go that route @johnotander, just let me know if you want to publish the scss addon, since it would be based almost entirely on this addon's code. If not, I'm happy to fork this and make it scss flavored.

**Comment by johnotander** [comment]
Thanks for the thoughtful response @scottrblock.

I think your conclusion that they should remain in separate addons is the right one, especially as I ponder it further. This way, each linter is easily pluggable by installing/uninstalling, and the concerns are separated.

It doesn't matter much to me whether I publish the scsslint addon or not. So, if you'd like to take the lead on/ownership of the scsslinting addon, @scottrblock, that'd be rad. Feel free to ping me if you need someone to collaborate with : ).

**Comment by scottrblock** [comment]
Woo, will get started!

**Comment by scottrblock** [comment]
A lot of this is likely due to my lack of ember-cli (and addon) experience, but I'm struggling a bit @johnotander.

The basic problem I can't seem to solve is how to correctly access the app's uncompiled .scss files, as opposed to the compiled css in `dist`. They don't seem to be in the tree in `postprocessTree`. I'm not sure if I should be trying to create the tree, or use a different hook. 

Looking at https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md, `treeForStyles` seems like it should work, but it doesn't seem to take a tree parameter, so I'm unsure how to access its tree when hooking in there. There's also a recently created `lintTree`, but that seems to be only js, not (s)css.

Any help would be appreciated!

**Comment by scottrblock** [comment]
Initial version up and running over at https://github.com/scottrblock/ember-cli-scsslint :smiley:

**Comment by johnotander** [comment]
Rad! Sorry I didn't reply before, got a bit bogged down in work, but it looks like you were able to get it all together. Awesome work!

**Comment by johnotander** [comment]
Closing this issue as it is now resolved. Separate addons for different preprocessors.
